### ISSUE TITLE
Add a section that talks about forward progress delegation

### ISSUE THREAD

**Issue by griwes** [NVIDIA/stdexec#146]
As mentioned by @ogiroux when we chatted about the words in #141, we should probably have a more central section about forward progress guarantees and how boost blocking and sync_wait relate to those.

**Comment by LeeHowes** [comment]
Taking bulk as the obvious example:
If it runs eagerly, it will launch more work on `get_completion_scheduler(sender)`.
If it runs lazily, it will launch more work on `get_scheduler(receiver)`. - TBD if this is a requirement of the runtime lazy choice or a guarantee for simplicity.

One option would then be to say that in either case, it is allowed to run work on `get_scheduler(receiver)`, which would allow delegation to sync_wait even under eager execution. This is questionable though because it would mean running on two schedulers, which could be problematic for correctness.

Another option is what I described in P1898 such that when we submit work to a scheduler, we are also providing a receiver on which we can call `get_scheduler(r)`. Trivially so in:

```
sync_wait(schedule(s) | then(f));
```

In that code, the sender returned by `schedule(s)` can call `get_scheduler(r)` and will end up with the `sync_wait` scheduler. `then` may or may not be eager, but I think what's important is that the instance of the eager scheduler actually has access to the second scheduler. 

In this case the scheduler is allowed to delegate any work enqueued to it to that downstream scheduler. It is scheduler-dependent whether that works, but that is always going to be true. Billy's Windows thread pool scheduler can *always* delegate to a `sync_wait` scheduler that represents a blocked waiting thread donating its time. 

In that way we don't need to do anything clunky like adding a thread to a thread pool, instead the scheduling interface itself can enable delegation in a very controlled and clean way.

It's also flexible. You could delegate from one CUDA stream to another CUDA stream, for example. I don't know if you'd ever want to, but you could do so through this mechanism.
