### ISSUE TITLE
sync_wait not handling void senders

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#228]
The return type of `sync_wait` is defined with:

```c++
template<typed_sender S>
  using sync-wait-type = optional<
    typename execution::sender_traits<remove_cvref_t<S>>
      ::template value_types<tuple, type_identity_t>>;
```

For a sender like `just_done()`, `value_types` is defined as:

```c++
template <template<class...> class, template<class...> class Variant>
using value_types = Variant<>;
```

The result of `sync_wait(just_done())` is a hard error because `type_identity_t` cannot be instantiated with 0 parameters.

If we decide we want this to compiler, we either need to change `sync_wait` or `just_done`.

**Comment by griwes** [comment]
IMHO this is fine. When we discussed the shape of sync_wait before deciding on what's in the paper, we've decided to make sync_wait only support senders that have a single set of values they send, and invented sync_wait_with_variant to handle them. If a user wants to sync_wait things like just_done(), they can use sync_wait_with_variant instead.

I'm okay with changing just_done() in some way to "fix" this (fix in quotes because I don't really think there's anything to fix here), but I would be against changing sync_wait - or at least against changing it in a way that makes the shape of the type returned from it not be exactly the same for all valid invocations of the algorithm.
