### ISSUE TITLE
about the name `unstoppable_token` and `stoppable_token`

### ISSUE THREAD

**Issue by huixie90** [NVIDIA/stdexec#321]
when I read
```
template<typename T>
  concept unstoppable_token =
    stoppable_token<T> && ...
```
, I feel that I am seeing a Schrodinger's cat

**Comment by lewissbaker** [comment]
Naming of these concepts was something that I struggled with.
We have the existing `stop_token` type.
We need a concept that generalises this type - `stoppable_token`.
We need a concrete stop-token type that represents something that can never receive a stop request - `never_stop_token`.
We need a concept that allows us to detect whether a given stoppable_token type can never receive a stop request (rather than just specialise on `never_stop_token`).
`unstoppable_token` seemed to match the naming convention of the use of the `...able` suffix to distinguish between concepts and types, but I agree it's potentially confusing since the name `unstoppable_token` implies the opposite of `stoppable_token` but is actually just a refinement.

Do you have any suggestions for a better names for `unstoppable_token` or `stoppable_token` concepts?
