### ISSUE TITLE
Should all receivers be moved into the completion signals?

### ISSUE THREAD

**Issue by msimberg** [NVIDIA/stdexec#422]
I don't know if this makes any difference in the wording, but there's currently quite a mix of how receivers are passed into completion signals:

- C-style cast (related: https://github.com/brycelelbach/wg21_p2300_std_execution/issues/379):
https://github.com/brycelelbach/wg21_p2300_std_execution/blob/e3627f3b90e914591cdf2d0a93aae98aa252eb27/std_execution.bs#L4520
- No move/cast:
https://github.com/brycelelbach/wg21_p2300_std_execution/blob/e3627f3b90e914591cdf2d0a93aae98aa252eb27/std_execution.bs#L4962
- Move:
https://github.com/brycelelbach/wg21_p2300_std_execution/blob/e3627f3b90e914591cdf2d0a93aae98aa252eb27/std_execution.bs#L5242

Should they all just be `std::move`d? Or something else? I'll happily attempt to clean this up (including #379).

**Comment by ericniebler** [comment]
The answer depends. When the algorithms mention `out_r`, what they should be saying is that they are manipulating an rvalue (or xvalue to be more precise) that refers to a copy of `out_r` that lives in <place>. ("<place>" most likely is within the operation state.) If for the sake of the specification, you give that rvalue a name like `out_r'`, then `out_r'` can appear in a `set_[value|error|stopped]` expression without a cast or a move, because it is already an rvalue.

Also see #403.

**Comment by ericniebler** [comment]
> I'll happily attempt to clean this up (including #379).

Oh, and in case it wasn't clear ... YES PLEASE. :-) #403 also, while you're at it.
