### ISSUE TITLE
get_env should be noexcept

### ISSUE THREAD

**Issue by anthonywilliams** [NVIDIA/stdexec#430]
`execution::get_env` should be specified to be `noexcept`, as this is a fundamental building block function for all the traits queries.
It should thus mandate that the `tag_invoke` expression is `noexcept` if it is customized.

**Comment by ericniebler** [comment]
This has implications for how environment objects are implemented and how the operation states store them. If an environment object must store an object with a potentially throwing copy constructor, it may require the operation state to store the environment object and return a reference to it in order to be `noexcept`.

**Comment by anthonywilliams** [comment]
Agreed. That seems reasonable to me. `get_env` should not be constructing objects that might fail to construct. Either it should return simple types, or references to objects with state.

**Comment by ericniebler** [comment]
Seems reasonable.
