### ISSUE TITLE
scheduler query for whether nested parallelism is supported/efficient

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#451]

**Comment by LeeHowes** [comment]
What does this mean? Is the question whether it is ok to do blocking parallelism within parallel tasks?

Presumably it would only apply to launching a synchronous parallel operation on the same scheduler as the parent?

**Comment by ericniebler** [comment]
I'm going to let @rarutyun and @senior-zero answer because I will probably fail to capture their intent accurately.

**Comment by rarutyun** [comment]
> What does this mean? Is the question whether it is ok to do blocking parallelism within parallel tasks?

Yes (if we are on the same page from terminology perspective)

> Presumably it would only apply to launching a synchronous parallel operation on the same scheduler as the parent?

That is the good question. I tend to say yes unless I realize other use-cases. But currently it's hard to imagine "nested parallelism" on different schedulers, so let's assume that we talk about the same one for now

**Comment by vossmjp** [comment]
I think it's a common case to have nested parallelism that uses different threading models. For example, you might have a library implemented using OpenMP that is called from a TBB parallel for. So we have to be careful to define what "efficient nested parallelism" means exactly. My guess is the query has to be about whether it's ok to create more parallelism using the same scheduler that created the outer parallelism, because otherwise I think its generally impossible to answer the question. So the cases of two schedulers exist, but that can't be what the query is about.

**Comment by LeeHowes** [comment]
Is it specifically related to *blocking* though or to the more general idea of enqueuing tasks recursively. The latter should presumably always be possible if the dependencies are safe, but might not be wise. The former would usually be impossible except in narrow cases, and require a lot of backchannelling of state to make it work at all, and I question the value of trying to specify it at all.
