### ISSUE TITLE
Compile error on transfer_just | bulk

### ISSUE THREAD

**Issue by mfbalin** [NVIDIA/stdexec#492]
I wanted to play around with senders&receivers and tried to improve on the async_inclusive_scan example by making it cache efficient. I have forked this repo and added my implementation but there seems to be a compile error. You can find my fork here: [my fork](https://github.com/mfbalin/wg21_p2300_std_execution)

[Source file of implementation](https://github.com/mfbalin/stdexec/blob/main/examples/scan.cpp)

To make it cache efficient, I take a block size and the threads first do the inclusive scan on the num_threads * block_size part before moving onto the later part of the problem so that only one read and write to the global memory happens.

The compile error I receive with gcc 11.1.0 seems to be cryptic and I don't really know how to resolve it.

[compile_error.txt](https://github.com/NVIDIA/stdexec/files/10806661/compile_error.txt)

Any guidance would be appreciated.

**Comment by prlw1** [comment]
An implementation of bulk and some improvements to it have just been committed, so you might like to have another go...

**Comment by mfbalin** [comment]
The compilation gets stuck now..., it doesn't work with neither g++-12 or clang++-14. I get segmentation fault somehow.

**Comment by bustercopley** [comment]
@mfbalin, the function can't be compiled because its return type is infinitely complex (the type contains itself, circularly). Here is a simpler program with the same feature, which also causes g++-12 to hang:

```
#include <tuple>

auto make_infinite_tuple(auto input) {
  return make_infinite_tuple(std::tuple_cat(input, std::tuple{0}));
}

int main() {
  auto x = make_infinite_tuple(std::tuple{0});
  return std::get<0>(x);
}
```

As for the original error message, I agree it's not very nice! I think it's telling you that the lambdas accepting `std::vector<T>&` can't be called with an rvalue reference.

**Comment by mfbalin** [comment]
How can I achieve my goal then, I changed the recursion into a while loop and now init_sender can not be overwritten with a sender of another type, that is next_init_sender in the code.

**Comment by bustercopley** [comment]
I'm not too sure. A very unimaginative answer is: type erasure. (You could look at `any_sender_of` in libunifex for inspiration.) Or maybe there is a way to use `bulk` again, but with `inline_scheduler` or something like it, as an 'outer loop'.

**Comment by mfbalin** [comment]
> I'm not too sure. A very unimaginative answer is: type erasure. (You could look at `any_sender_of` in libunifex for inspiration.) Or maybe there is a way to use `bulk` again, but with `inline_scheduler` or something like it, as an 'outer loop'.

@bustercopley, I recently saw the merged pull request for any_sender_of #771 and used it to type erase the potentially infinitely complex sender type. But it seems like I am still getting a compile error.

**Comment by maikel** [comment]
Hi, I have only looked briefly in the code but I've spotted several problems:

To use any_sender you either need to also specify allow exceptions in the completion sigs or you mark at least all your lambdas noexcept. The then algorithm will add exceptions otherwise and then you can't bind to an any_sender which doesnt explicitly allow that.

Another issue is that you assign into the any_sender without ever connecting or chaining them, or do I misread that?

I also think you initialize your tile vector with wrong braces? I don't if that fixes everything but it might give you another starting point.

Cheers,
Maikel

**Comment by maikel** [comment]
Oh, and any_sender is a move only type and models a single shot sender. So you need to move it into when_all. And then move that sender back into the type erased one.

**Comment by mfbalin** [comment]
Thank you very much Maikel for pointing me in the right direction. I am an enthusiastic user and wanted to see if I could use the senders and receivers model to implement a non-trivial algorithm. However, the compiler is giving me hell, I can't understand half of what it is spitting out for me 😄. Below, you can find the updated compile error after attempting to incorporate your suggested changes into [my implementation](https://github.com/mfbalin/stdexec/blob/main/examples/scan.cpp).

[compile_error.txt](https://github.com/NVIDIA/stdexec/files/10809228/compile_error.txt)

**Comment by maikel** [comment]
You are almost there. Change 

```
any_sender_of<set_value_t(T)> init_sender
```
to
```
any_sender_of<set_value_t(T), set_stopped_t(), set_error_t(std::exception_ptr)> init_sender
```

and also dont forget move senders in your main function

```
  sender auto scan_back_on = on(sch, std::move(scan_back));

  auto back = this_thread::sync_wait(std::move(scan_back_on));
```

I just tested that changes with your code here https://godbolt.org/z/axe39vh73
and it compiles for *clang*. There seems to be a bug for GCC. I will look into that
