### ISSUE TITLE
`run_loop` task ownership

### ISSUE THREAD

**Issue by switch-blade-stuff** [NVIDIA/stdexec#883]
From reading the proposal, it seems to me that the lifetime of senders must not exceed the lifetime of their `run_loop` (point 2 of `class run-loop-sender` in `[exec.run_loop.types]`).

However, the allocation-free requirement (and the reference implementation) suggests that both the scheduler & senders are stack-allocated. This will cause use-after-free issues with `run_loop`s that do not share stack frames with the schedulers (or are heap-allocated).

For example, in `1.6.2`, implementation of `single_thread_context` uses a `run_loop` in conjunction with a thread. However, nothing prevents the use of `single_thread_context` as an externally-allocated object, and that would definitely cause use-after-free issues.

In my opinion, if `run_loop` is only intended to be used as a stack-local and cannot outlive it's schedulers, this should be communicated within the proposal and the API. This also limits the usefulness of `run_loop` and other contexts that use it, as now they can only be used within a single stack frame, and for example, cannot be passed as a parameter to other functions and algorithms.

**Comment by ericniebler** [comment]
This is by design. Senders are designed for structured concurrency. Each async operation can have child operations whose lifetimes nest within that of the parent. A `run_loop` owned by one operation can be safely used by any of that operation's children, exactly like a local variable in a coroutine.

C++ object semantics are also built around the static structure of your program. A function can safely pass a reference to a local to a callee because we know the callee will complete before the local is destroyed.

It's true that with dynamic allocations, objects can be left holding dangling pointers, but we don't make that a problem of the C++ object model. We could though. We could dynamically allocate and reference count everything, or implement garbage collection. But we don't.

And we shouldn't with sender/receiver either.
