### ISSUE TITLE
Can't compile with coroutine header

### ISSUE THREAD

**Issue by weilewei** [NVIDIA/stdexec#949]
Hi,

What are the recommended flags to compile program with sender + coroutine?

I would like to write a program that integrates sender + coroutine, but I ran into issue compiling it.

Program:
```
#include <stdexec/execution.hpp>
#include <exec/static_thread_pool.hpp>
#include <vector>
#include <iostream>
#include <ranges>
#include <coroutine>

int main() {}
```

Flags combo 1:
```
wwei@login39:~/src/test-snd> nvc++ -std=c++20 --experimental-stdpar -c main.cpp main
main.cpp:
"/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/include-stdexec/experimental/stdexec/__detail/__config.hpp", line 19: catastrophic error: #error directive: This library requires the use of C++20.
  #error This library requires the use of C++20.
   ^

1 catastrophic error detected in the compilation of "main.cpp".
Compilation terminated.
```

Flags combo 2 based on combo1 plus `--gcc-toolchain`:
```
wwei@login39:~/src/test-snd> nvc++ -std=c++20 --experimental-stdpar --gcc-toolchain=/opt/cray/pe/gcc/12.2.0/bin/ -c main.cpp main
main.cpp:
"/opt/cray/pe/gcc/12.2.0/snos/include/g++/coroutine", line 361: catastrophic error: #error directive: "the coroutine header requires -fcoroutines"
  #error "the coroutine header requires -fcoroutines"
   ^

1 catastrophic error detected in the compilation of "main.cpp".
Compilation terminated.
```

flags combo 3 based on combo2 plus `-fcoroutines`:
```
wwei@login39:~/src/test-snd> nvc++ -std=c++20 --experimental-stdpar --gcc-toolchain=/opt/cray/pe/gcc/12.2.0/bin/ -fcoroutines -c main.cpp main
nvc++-Error-Unknown switch: -fcoroutines
```

**Comment by ericniebler** [comment]
Could you send me the output of `nvc++ --version`?

**Comment by weilewei** [comment]
wwei@login32:~> nvc++ --version
nvc++ 23.1-0 64-bit target on x86-64 Linux -tp zen3 
NVIDIA Compilers and Tools
Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

I am running on Perlmutter supercomputer at NERSC hosted at Lawrence Berkeley National Lab.

**Comment by ericniebler** [comment]
I don't understand the error you are seeing for the first set of flags. The same code with the same compiler version and the same flags compiles fine on godbolt.org (minus the `#include <coroutine>`): https://godbolt.org/z/M78nWd796

A `#include <coroutine>` is going to pull in the coroutine header from your system toolchain, which knows nothing about nvc++. The header is doing a feature test for coroutines, finding they aren't supported, and is issuing a diagnostic that would make sense for the system toolchain: "add `-fcoroutines`". That would work if you were compiling with g++, but you're not. It's garbage advice for nvc++, which is why it doesn't work for you.

The nvc++ team is actively working on coroutine support, so expect it soon. Until then, the only way to use coroutines and CUDA in the same program is to use clang's CUDA support.

Hope that helps.

**Comment by weilewei** [comment]
If we remove `#include <coroutine>`, then

flags combo 1
```
wwei@login01:~/src/test-snd> nvc++ -std=c++20 --experimental-stdpar -c main.cpp main
main.cpp:
"/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/include-stdexec/experimental/stdexec/__detail/__config.hpp", line 19: catastrophic error: #error directive: This library requires the use of C++20.
  #error This library requires the use of C++20.
   ^

1 catastrophic error detected in the compilation of "main.cpp".
Compilation terminated.
```
flag combo 2
```
wwei@login01:~/src/test-snd> nvc++ -std=c++20 --experimental-stdpar --gcc-toolchain=/opt/cray/pe/gcc/12.2.0/bin/ -c main.cpp main
main.cpp:
```

**Comment by ericniebler** [comment]
Please look at the link I sent in my last comment. It's nvc++ 23.1 with the exact flags from combo #1. It's on godbolt.org so you don't have to take my word for it. It objectively works. It also works locally on my machine.

I'm willing to bet that there is something off about how your toolchain is configured.

**Comment by weilewei** [comment]
Yeah, I did look into your link. I think it might be the issue with nvc++ 23.1 on our machine, let me redirect the ticket to nvhpc team. Thanks.
